#include "typelist.h"
#include <stdio.h>
#include <string.h>


/* This builds a test for argument passing and returning of scalar types.  */

/* Maximum number of arguments.  */
#define MAXIMUM_ARGS   24

struct TestSetting
{
  int reg_count;   /* Amount of registers for argument passing.  */
  char reg_prefix; /* Prefix used in the argument passing sequence in args.h */
  char arg_prefix; /* Prefix for functions, macros and the Register struct.  */
  char string[20]; /* "int" or "float".  */
};
struct TestSetting test_setting[2];

#define INT_TEST   0
#define FLOAT_TEST 1

void
init_test_settings ()
{
  test_setting[INT_TEST].reg_count = 6;
  test_setting[INT_TEST].reg_prefix = 'I';
  test_setting[INT_TEST].arg_prefix = 'i';
  strcpy(test_setting[INT_TEST].string, "int");

  test_setting[FLOAT_TEST].reg_count = 16;
  test_setting[FLOAT_TEST].reg_prefix = 'F';
  test_setting[FLOAT_TEST].arg_prefix = 'f';
  strcpy(test_setting[FLOAT_TEST].string, "float");
}


/* Make top of the file.  */
void
make_file_start ()
{
  int i;

  printf ("/* This is an autogenerated file. Do not edit.  */\n\n");
  printf ("#include \"defines.h\"\n#include \"macros.h\"\n");
  printf ("#include \"funcs.h\"\n#include \"args.h\"\n\n");
  printf ("/* This struct holds values for argument checking.  */\n");
  printf ("struct Values\n{\n  long i0");
  for (i=1; i<MAXIMUM_ARGS; i++)
    printf (", %c%d", test_setting[INT_TEST].arg_prefix, i);
  printf (";\n  double f0");
  for (i=1; i<MAXIMUM_ARGS; i++)
    printf (", %c%d", test_setting[FLOAT_TEST].arg_prefix, i);
  printf (";\n} values;\n\n");
}


/* Construct the two test functions for testing argument passing.  */
void
make_checking_function (int test_type, char *type, int arg_count)
{
  int i;
  char arg_prefix = test_setting[test_type].arg_prefix;
  char *type_str = test_setting[test_type].string;

  /* Values test.  */
  printf ("void\nfun_check_%s_passing_%s%d_values (", type_str, type,
	  arg_count);
  for (i=0 ; i<arg_count; i++) {
    if (i != 0)
      printf(", ");
    printf ("%s %c%d", type, arg_prefix, i);
  }
  printf (")\n{\n");
  printf ("  /* Check argument values.  */\n");
  for (i=0; i<arg_count; i++)
    printf ("  assert (values.%c%i == %c%i);\n", arg_prefix, i, arg_prefix, i);
  printf ("\n}\n\n");

  /* Registers test.  */
  printf ("void\nfun_check_%s_passing_%s%d_regs (", type_str, type, arg_count);
  for (i=0 ; i<arg_count; i++) {
    if (i != 0)
      printf(", ");
    printf ("%s %c%d", type, arg_prefix, i);
  }
  printf (")\n{\n");
  printf ("  /* Check register contents.  */\n");
  printf ("  check_%s_register_contents;\n}\n\n", type_str);
}

/* Make the functions testing the passing.  */
void
make_test_funcs ()
{
  make_checking_function (INT_TEST, "int", 6);
  make_checking_function (INT_TEST, "int", 12);
  make_checking_function (INT_TEST, "long", 6);
  make_checking_function (INT_TEST, "long", 12);
#ifdef CHECK_LARGE_SCALAR_PASSING
#ifdef CHECK_INT128
  make_checking_function (INT_TEST, "__int128", 3);
  make_checking_function (INT_TEST, "__int128", 12);
#endif
#endif

  make_checking_function (FLOAT_TEST, "float", 8);
  make_checking_function (FLOAT_TEST, "float", 16);
  make_checking_function (FLOAT_TEST, "float", 20);
  make_checking_function (FLOAT_TEST, "double", 8);
  make_checking_function (FLOAT_TEST, "double", 16);
  make_checking_function (FLOAT_TEST, "double", 20);
#ifdef CHECK_LARGE_SCALAR_PASSING
#ifdef CHECK_FLOAT128
  make_checking_function (FLOAT_TEST, "__float128", 4);
  make_checking_function (FLOAT_TEST, "__float128", 8);
  make_checking_function (FLOAT_TEST, "__float128", 10);
#endif
#ifdef CHECK_LONG_DOUBLE
  make_checking_function (FLOAT_TEST, "long double", 8);
  make_checking_function (FLOAT_TEST, "long double", 16);
  make_checking_function (FLOAT_TEST, "long double", 20);
#endif
#endif
}


/* Construct a macro used to test argument passing.  */
void
make_checking_define (int test_type, int arg_count)
{
  int i;
  int max_regs = test_setting[test_type].reg_count;
  char arg_prefix = test_setting[test_type].arg_prefix;
  char reg_prefix = test_setting[test_type].reg_prefix;
  char *type_str = test_setting[test_type].string;

  /* Print define header.  */
  printf ("#define def_check_%s_passing%d(", type_str, arg_count);
  for (i=0; i<arg_count; i++)
    printf ("_%c%d, ", arg_prefix, i);
  printf ("_func1, _func2) \\\n");

  /* Test actual parameters' values, also for those passed on the stack.  */
  for (i=0; i<arg_count; i++)
    printf ("  values.%c%d = _%c%d; \\\n", arg_prefix, i, arg_prefix, i);
  printf ("  _func1 (");
  for (i=0; i<arg_count; i++)
    {
      if (i != 0)
	printf (", ");
      printf ("_%c%d", arg_prefix, i);
    }
  printf ("); \\\n  \\\n");

  /* Test values passed in registers.  */
  printf ("  clear_%s_registers; \\\n", type_str);
  for (i=0; i<arg_count && i<max_regs; i++)
    printf ("  %cregs.%c%d = _%c%d; \\\n", arg_prefix, reg_prefix, i,
	    arg_prefix, i);

  /* Make function call.  */
  printf ("  _func2 (");
  for (i=0; i<arg_count; i++)
    {
      if (i != 0)
	printf (", ");
      printf ("_%c%d", arg_prefix, i);
    }
  printf (");\n\n");
}

void
make_test_defs ()
{
  /* Make defines for integer-type functions.  */
  make_checking_define (INT_TEST, 6);
  make_checking_define (INT_TEST, 12);

  /* Make defines for floating-type point functions.  */
  make_checking_define (FLOAT_TEST, 8);
  make_checking_define (FLOAT_TEST, 16);
  make_checking_define (FLOAT_TEST, 20);
}


/* This makes a call to the defined macro with arg_count arguments. The
   arguments values are a 32, 33, 34...  */
void
make_test (char *name, int test_type, char *type, int arg_count)
{
  int i;
  char *type_str = test_setting[test_type].string;

  printf ("void\n%s ()\n{\n", name);
  printf ("  def_check_%s_passing%d(", type_str, arg_count);
  for (i=0; i<arg_count; i++)
    printf ("%d, ", 32+i);
  printf ("fun_check_%s_passing_%s%d_values, ", type_str, type, arg_count);
  printf ("fun_check_%s_passing_%s%d_regs);\n}\n\n", type_str, type,
	  arg_count);
}

/* Make two tests in one function.  */
void
make_test2 (char *name, int test_type, char *type, int count1, int count2)
{
  int i;
  char *type_str = test_setting[test_type].string;

  printf ("void\n%s ()\n{\n", name);

  printf ("  def_check_%s_passing%d(", type_str, count1);
  for (i=0; i<count1; i++)
    printf ("%d, ", 32+i);
  printf ("fun_check_%s_passing_%s%d_values, ", type_str, type, count1);
  printf ("fun_check_%s_passing_%s%d_regs);\n\n", type_str, type, count1);

  printf ("  def_check_%s_passing%d(", type_str, count2);
  for (i=0; i<count2; i++)
    printf ("%d, ", 32+i);
  printf ("fun_check_%s_passing_%s%d_values, ", type_str, type, count2);
  printf ("fun_check_%s_passing_%s%d_regs);\n}\n\n", type_str, type, count2);
}

/* This outputs an empty function. Used by disabled tests.  */
void
make_empty_tests (char *type)
{
  printf ("void\ntest_%ss_on_stack ()\n{\n}\n\n", type);
  printf ("void\ntest_too_many_%ss ()\n{\n}\n\n", type);
}

void
make_int_tests ()
{
  make_test ("test_ints_on_stack", INT_TEST, "int", 6);
  make_test ("test_too_many_ints", INT_TEST, "int", 12);

  make_test ("test_longs_on_stack", INT_TEST, "long", 6);
  make_test ("test_too_many_longs", INT_TEST, "long", 12);

#if defined CHECK_LARGE_SCALAR_PASSING && defined CHECK_INT128
  make_test ("test_int128s_on_stack", INT_TEST, "__int128", 3);
  make_test ("test_too_many_int128s", INT_TEST, "__int128", 10);
#else
  make_empty_tests ("int128");
#endif
}

void
make_float_tests ()
{
  make_test2 ("test_floats_on_stack", FLOAT_TEST, "float", 8, 16);
  make_test ("test_too_many_floats", FLOAT_TEST, "float", 20);

  make_test2 ("test_doubles_on_stack", FLOAT_TEST, "double", 8, 16);
  make_test ("test_too_many_doubles", FLOAT_TEST, "double", 20);

#if defined CHECK_LARGE_SCALAR_PASSING && CHECK_LONG_DOUBLE
  make_test ("test_long_doubles_on_stack", FLOAT_TEST, "long double", 8);
  make_test ("test_too_many_long_doubles", FLOAT_TEST, "long double", 20);
#else
  make_empty_tests ("long_double");
#endif

#if defined CHECK_LARGE_SCALAR_PASSING && CHECK_FLOAT128
  make_test ("test_float128s_on_stack", FLOAT_TEST, "__float128", 8);
  make_test ("test_too_many_float128s", FLOAT_TEST, "__float128", 20);
#else
  make_empty_tests ("float128");
#endif
}

/* Add tests for both integer and floating point arguments.  */
void
make_mixed_tests ()
{
}

/* Construct the file.  */
int
main (int argc, char **argv)
{
  init_test_settings ();
  init_typelist ();

  make_file_start ();

  make_test_funcs ();
  make_test_defs ();

  make_int_tests ();
  make_float_tests ();
  make_mixed_tests ();

  return 0;
}
