#include "typelist.h"
#include <stdio.h>
#include <string.h>


/* This builds the tests for returning arguments.  */


/* Small helper function that prints spaces as '_'.  */
void
print_no_spaces (const char *str)
{
  const char *c = str;

  while (*c)
    {
      if (*c == ' ')
	printf ("_");
      else
	printf ("%c", *c);

      c++;
    }
}


/* Make top of the file.  */
void
make_file_start ()
{
  printf ("/* This is an autogenerated file. Do not edit.  */\n\n");
  printf ("#include \"defines.h\"\n");
  printf ("#include \"macros.h\"\n");
  printf ("#include \"args.h\"\n\n");
}

void
make_testing_callee (const char *type, const char *args, const char *ret)
{
  printf ("%s\nfun_test_returning_", type);
  print_no_spaces (type);
  printf (" (%s)\n{\n  return %s;\n}\n\n", args, ret);
}

void
make_testing_caller ()
{
  printf ("#define def_test_returning_type_xmm(fun, type, ret, reg) \\\n");
  printf ("  WRAP_RET (fun) (); \\\n");
  printf ("  assert (ret == (type) reg);\n");
}

void
make_test_functions ()
{
  int i;
  char args[100];
  char ret[100];

  /* Make scalar return test functions.  */
  for (i=0; i<typecount; i++) {
    sprintf (args, "void");
    sprintf (ret, "%d", i+64);
    make_testing_callee (types[i], args, ret);
  }

  /* Make struct return test functions.  */
  /* TODO: This.  */
}

void
make_test_scalar_returning ()
{
  int i;

  /* Print out the header of the function.  */
  printf ("int\nmain (void)\n{\n");

  /* Make the tests.  */
  for (i=0; i<typecount; i++) {
    printf ("  def_test_returning_type_xmm");
    printf ("(fun_test_returning_");
    print_no_spaces (types[i]);
    printf (", %s, %d, %s);\n", types[i], i+64, returns[i]);
  }

  printf ("  return 0;\n}\n");
}

void
make_test_struct_returning ()
{
}

int
main (int argc, char **argv)
{
  init_typelist ();

  make_file_start ();

  make_test_functions ();
  make_testing_caller ();
  make_test_scalar_returning ();

  /* TODO: Test structs and unions return.  */
  make_test_struct_returning ();

  return 0;
}
