/* This tests passing of basic types to functions. It does this by comparing
   all registers to their expected values. TODO: Test that only caller owned
   registers get their values changed.  
   Presently the register passing sequence is rsi, rdi, rdx, rcx, r8, r10.  
   Macros are used to avoid register clobbering.  */

#include "args.h"

struct Registers regs;


/* Check hardware registers against the struct. This will probably later
   be a list of macros with autogenerated calls to them.  */
void check_hardware_registers1(int i0)
{
    check_register_contents;
}
void check_hardware_registers2(int i1, int i0)
{
    check_register_contents;
}
void check_hardware_registers3(char i1, int i0)
{
    check_register_contents;
}
void check_hardware_registers4(int i2, short i1, int i0)
{
    check_register_contents;
}
void check_hardware_registers5(long i4, long i3, long i2, int i1, int i0)
{
    check_register_contents;
}
void check_hardware_registers6(long i5, long i4, int i3, long i2, int i1,
			       int i0)
{
    check_register_contents;
}

#define check_args1(i0) \
    clear_registers; \
    regs.I0 = i0; \
    check_hardware_registers1(i0);

#define check_args2(i0, i1) \
    clear_registers; \
    regs.I0 = i0; regs.I1 = i1; \
    check_hardware_registers2(i0, i1);

#define check_args3(i0, i1) \
    clear_registers; \
    regs.I0 = i0; regs.I1 = i1; \
    check_hardware_registers3(i0, i1);

#define check_args4(i0, i1, i2) \
    clear_registers; \
    regs.I0 = i0; regs.I1 = i1; regs.I2 = i2; \
    check_hardware_registers4(i0, i1, i2);

#define check_args5(i0, i1, i2, i3, i4) \
    clear_registers; \
    regs.I0 = i0; regs.I1 = i1; regs.I2 = i2; regs.I3 = i3; regs.I4 = i4; \
    check_hardware_registers5(i0, i1, i2, i3, i4);

#define check_args6(i0, i1, i2, i3, i4, i5) \
    clear_registers; \
    regs.I0 = i0; regs.I1 = i1; regs.I2 = i2; regs.I3 = i3; regs.I4 = i4; \
    regs.I5 = i5; check_hardware_registers6(i0, i1, i2, i3, i4, i5);

void
scalarargs (void)
{
    check_args1(32);
    check_args2(32, 33);
    check_args3(32, 33);
    check_args4(32, 33, 34);
    check_args5(32, 33, 34, 35, 36);
    check_args6(32, 33, 34, 35, 36, 37);
}
